[package]
name = "yehong-wan/mygame"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2.0.3"
Sift = "csqrl/sift@0.0.11"
DataService = "leifstout/dataservice@1.0.0"
Networker = "leifstout/networker@0.3.1"
Charm = "littensy/charm@0.10.0"
ReactCharm = "littensy/react-charm@0.3.0"
ServicePlayerData = "leifstout/serviceplayerdata@0.1.2"
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
Janitor = "howmanysmall/janitor@1.18.3"
Ripple = "littensy/ripple@0.10.2"
ReactRipple = "littensy/react-ripple@3.0.1"
ByteNetMax = "elitriare/bytenet-max@0.2.1"
UILabs = "pepeeltoro41/ui-labs@2.4.2"